spring:
  application:
    name: zxyz-project-service
  config:
    import:
      - classpath:application-common.yml
      - nacos:zxyz-static.yml?group=ZXYZ&refreshEnabled=false
      - nacos:zxyz-dynamic.yml?group=ZXYZ&refreshEnabled=true
      - nacos:zxyz-project-service.yml?group=ZXYZ&refreshEnabled=false
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yml
        group: ZXYZ
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: ${SERVER_PORT:18080}

app:
  performance:
    time-aspect-enabled: true
  file-object-delete:
    enabled: true
    batch-size: 20
    initial-delay-ms: 30000
    retry-fixed-delay-ms: 60000
  im:
    base-url: ${services.im-service.base-url}
  file-service:
    base-url: ${services.file-service.base-url}
  team-service:
    base-url: ${services.team-service.base-url}
  user-service:
    base-url: ${services.user-service.base-url}
  email-service:
    base-url: ${services.email-service.base-url}
