spring:
  application:
    name: zxyz-audit-service
  config:
    import:
      - classpath:application-common.yml
      - nacos:zxyz-static.yml?group=ZXYZ&refreshEnabled=false
      - nacos:zxyz-dynamic.yml?group=ZXYZ&refreshEnabled=true
      - nacos:zxyz-audit-service.yml?group=ZXYZ&refreshEnabled=false
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yml
        group: ZXYZ
  profiles:
    default: dev
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

