spring:
  config:
    import:
      - classpath:application-common.yml
      - nacos:zxyz-static.yml?group=ZXYZ&refreshEnabled=false
      - nacos:zxyz-dynamic.yml?group=ZXYZ&refreshEnabled=true
      - nacos:zxyz-team-service.yml?group=ZXYZ&refreshEnabled=false
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yml
        group: ZXYZ
  profiles:
    default: dev
  application:
    name: zxyz-team-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TEAM_DATASOURCE_URL}
    username: ${TEAM_DATASOURCE_USERNAME}
    password: ${TEAM_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: ${SERVER_PORT:18086}

app:
  user-service:
    base-url: ${services.user-service.base-url}
  im-service:
    base-url: ${services.im-service.base-url}
  email-service:
    base-url: ${services.email-service.base-url}
  file-service:
    base-url: ${services.file-service.base-url}
  project-service:
    base-url: ${services.project-service.base-url}
